

setGeneric('connection', function(x, ...) standardGeneric('connection'))
setGeneric('connection<-', function(x, value, ...) standardGeneric('connection<-'))
setGeneric('remoteName', function(x, ...) standardGeneric('remoteName'))
# setGeneric('remoteName<-', function(x, value, ...) standardGeneric('remoteName<-'))
setGeneric('reconnect', function(x, ...) standardGeneric('reconnect'))
setGeneric('disconnect', function(x, ...) standardGeneric('disconnect'))
setGeneric('driver', function(x, ...) standardGeneric('driver'))
setGeneric('driver<-', function(x, ...) standardGeneric('driver<-'))
setGeneric('query', function(x, statement, ...) standardGeneric('query'))
setGeneric('queryStack', function(x, ...) standardGeneric('queryStack'))
setGeneric('queryStack<-', function(x, value, ...) standardGeneric('queryStack<-'))
setGeneric('remoteValid', function(x, ...) standardGeneric('remoteValid'))
setGeneric('remoteListTables', function(x, ...) standardGeneric('remoteListTables'))
setGeneric('remoteExistsTable', function(x, remote_name, ...) standardGeneric('remoteExistsTable'))
setGeneric('setRemoteKey', function(x, remote_name, primary_key, ...) standardGeneric('setRemoteKey'))
